
# Tool path
__PATH__ = /opt/CodeSourcery/Sourcery_G++_Lite


# GNU C compiler path
__GCC__  = $(__PATH__)/bin/arm-none-eabi-gcc


# C Preprocessor path
__CPP__  = $(__PATH__)/bin/arm-none-eabi-cpp


all:
	$(__CPP__) UserMain2.c -o result1.i
	
clean:
	rm -rf result1.i
